- name: copy file to the Ansible Automation Platform
  hosts: all  
  become: yes
  tasks:
    - name: Copy the hostname file on the Ansible Automation Platform server
      fetch:
        src: "/tmp/a.txt"
        dest: "/opt/a/"
        owner: awx
        group: awx
        mode: '0775'
        flat: yes
